name: Caller

on:
  workflow_dispatch: {}
  pull_request:
    branches: main

jobs:
  internal:
    uses: makar2/poc-github-actions/.github/workflows/_call-recipient-1.yml@main

  external:
    uses: makar2/for-poc-github-actions/.github/workflows/_call-recipient-2.yml@main
